import_data:
  url: "//FLICKAT1-WL1/dvc_source_data_test/"
linear_model: 
  name: Linear
ridge_model: 
  name: Ridge
  alpha: "0.001 0.01 0.1 1.0 10.0 100.0 1000.0"
  solver: "auto"
lasso_model: 
  name: Lasso
  alpha: "0.1 1.0"
random_forest_model: 
  name: RandomForest
  n_estimators: "10 50"
  max_depth: "10 20"
